---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: Install firewalld
      yum: 
        name: firewalld
        state: latest
    - name: Install telnet
      yum:
        name: telnet
        state: latest
    - name: Add user bob
      user:
        name: bob
        state: present
        comment: "Bob Smith"
        group: wheel
        uid: 2001
        create_home: yes
        expires: 1438798
        generate_ssh_key: yes
    - name: Install lftp
      package:
        name: lftp
        state: present
     - name: Install multiple users
      user:
      package:
        name: "{{item}}"
        state: present
      with_items:
        - bob
        - sam
        - ben
        - tim
     - name: Install multiple packages
      package:
        name: "{{item}}"
        state: present
      with_items:
        - mariadb-server
        - php
        - httpd
        - curl
        - gzip
        - httpd
        - openssh-server
    




