---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install multiple users
      user:
      package:
        name: "{{item}}"
        state: present
      with_items:
        - bob
        - sam
        - ben
        - tim