---
- name: Playbook for sec group
  hosts: localhost
  tasks:
    - name: Create Sec Group
      ec2_group:
        name: SecGroup
        description: Sec Group 1
        vpc_id: vpc-e4243182
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
           - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
