---
- name: Playbook for sec group
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create IGW
      ec2_vpc_igw:
        region: us-east-1
        vpc_id: vpc-abcdekjk
        state: present
      register: igw